### ISSUE TITLE
osc wrong channel number

### ISSUE THREAD

**Issue by micuat** [I-CubeX/PythonExamples#1]
Hi Johnty,

https://github.com/I-CubeX/PythonExamples/blob/master/AnalogReadOSC.py#L36

this should be range(0, NUM_CH) to get all the 8 channels...

**Comment by johnty** [comment]
thanks naoto!
  fixed in [c903de](https://github.com/I-CubeX/PythonExamples/commit/c903de98f5ededf708bc48bdad78cd2f28237091)
